### ISSUE TITLE
Error: Expected {} to be {}

### ISSUE THREAD

**Issue by diegodesouza** [mjackson/expect#91]
I'm not sure this is the intended behavior, but i have this going on. 
``` 
it('should validate item', () => {
  let message = validate(validItem)

  expect(message).toBe({})
})
```

I am passing a valid item to a validation function where the message should be and empty object or `{}` in this case. So i'm using the above expectation. I'm getting this error. 

```
1) validate should validate item:
     Error: Expected {} to be {}
      at assert (node_modules/expect/lib/assert.js:22:9)
      at Expectation.toBe (node_modules/expect/lib/Expectation.js:64:28)
      at Context.<anonymous> (item_form.spec.js:16:21)
```

Is it my logic that is flawed or is that a bug? Thanks

**Comment by diegodesouza** [comment]
Okay so `toBe` evaluates the object using `===` 
```Asserts that object is strictly equal to value using ===```
So i tried this in the console
```
{} === {}
false
```

as we can see it returns false. So it's not expect's fault.
